import { withAuthenticator } from "@aws-amplify/ui-react";

import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";

const inter = Inter({ subsets: ["latin"] });

type Props = {
    signOut: any;
    user: any;
    renderedAt: string;
};

function Home({ signOut, user, renderedAt }: Props) {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className="">
                <div style={{ padding: 50 }}>
                    <h1>Logged in as {user.username}.</h1>
                    <div>
                        <button onClick={signOut}>Sign out</button>
                    </div>
                    <p>This page was server-side rendered on {renderedAt}.</p>
                </div>
            </main>
        </>
    );
}

export function getServerSideProps() {
    const renderedAt = new Date();
    const formattedBuildDate = renderedAt.toLocaleDateString("en-US", {
        dateStyle: "long",
    });
    const formattedBuildTime = renderedAt.toLocaleTimeString("en-US", {
        timeStyle: "long",
    });
    return {
        props: {
            renderedAt: `${formattedBuildDate} at ${formattedBuildTime}`,
        },
    };
}

export default withAuthenticator(Home);
