import { withAuthenticator } from '@aws-amplify/ui-react';

import Head from 'next/head';
import Image from 'next/image';
import { Inter } from '@next/font/google';

import UserProfile from '@/components/auth/UserProfile';
import ColorCreateForm from '@/ui-components/ColorCreateForm';

const inter = Inter({ subsets: ['latin'] });

type Props = {
    signOut: any;
    user: any;
    renderedAt: string;
};

function Home({ signOut, user, renderedAt }: Props) {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className="h-auto">
                <div className="h-screen">
                    <div className="flex min-h-full">
                        <UserProfile />
                    </div>
                </div>
            </main>
        </>
    );
}

export function getServerSideProps() {
    const renderedAt = new Date();
    const formattedBuildDate = renderedAt.toLocaleDateString('en-US', {
        dateStyle: 'long',
    });
    const formattedBuildTime = renderedAt.toLocaleTimeString('en-US', {
        timeStyle: 'long',
    });
    return {
        props: {
            renderedAt: `${formattedBuildDate} at ${formattedBuildTime}`,
        },
    };
}

export default Home;

// export default withAuthenticator(Home);
